import type { Experience } from "@/types";

export const personalProjects: Experience[] = [
  {
    date: "August 2025",
    title: "Deathmatch Agents",
    github: "https://github.com/mikelneonedwin/deathmatch-agents",
    description: [
      "Prototype project exploring low-level concepts: IPCs, CPU allocation/scheduling, I/O and CPU bursts, signals, and more",
      "Multi-language agent orchestration in a competitive 'deathmatch' environment",
      "Current implementation in TypeScript; other languages will be added",
    ],
    technologies: ["TypeScript"],
  },
  {
    date: "August 2025",
    title: "JZ",
    github: "https://github.com/mikelneonedwin/JZ",
    description: [
      "GUI version of JQuiz built with Java",
      "Uses Swing for the interface and PostgreSQL for persistence",
    ],
    technologies: ["Java", "Swing", "PostgreSQL"],
  },
  {
    date: "May 2025",
    title: "Icebreaker",
    website: "http://ice-break-er.vercel.app/",
    github: "https://github.com/mikelneonedwin/icebreaker",
    description: [
      "List of questions in different categories to keep conversations going with friends",
    ],
    technologies: ["React", "TypeScript", "Vite", "TailwindCSS"],
  },
  {
    date: "March 2025",
    title: "Voysa (Lead Frontend Dev)",
    company: "Team Voysa",
    location: "University of Uyo",
    website: "https://voysa.vercel.app",
    github: "https://github.com/mikelneonedwin/voysa",
    description: [
      "Social platform project, winner of SuiOverflow Hackathon at Uniuyo 2025",
      "Led frontend development and built scalable UI with React and Vite",
    ],
    technologies: ["Vite", "React", "TypeScript", "TailwindCSS"],
  },
  {
    date: "January 2025",
    title: "Rock Paper Scissors Simulator",
    website: "https://rps-sim.vercel.app",
    github: "https://github.com/mikelneonedwin/rps-sim",
    description: [
      "Web-based rock–paper–scissors game",
      "Built as a fun, interactive project",
    ],
    technologies: ["React", "TypeScript", "Vite", "TailwindCSS"],
  },
  {
    date: "October 2024",
    title: "Thrivr Landing Page",
    company: "Thrivr",
    location: "Remote",
    website: "https://ayo-test.vercel.app",
    github: "https://github.com/mikelneonedwin/ayo-test",
    description: [
      "Landing page built from scratch as part of internship application for Thrivr",
      "Focused on clean, responsive UI and performance",
    ],
    technologies: ["Next.js", "React", "TypeScript", "TailwindCSS"],
  },
  {
    date: "2024 – Ongoing",
    title: "Vantage (Team Lead)",
    company: "Team Vantage",
    location: "University of Uyo",
    description: [
      "Educational tool for students providing AI-assisted learning",
      "Winner of GDGOC Uniuyo EduSolutions Hackathon 2024",
      "Goal: leverage AI to enhance studying and personalized learning",
    ],
    technologies: [
      "Next.js",
      "Supabase",
      "Vercel AI SDK",
      "React",
      "TypeScript",
    ],
  },
  {
    date: "October 2023",
    title: "30 V3 Submission Portal",
    company: "30DaysOfCodeWithVickyJay",
    location: "Remote",
    website: "https://v3-bice.vercel.app",
    github: "https://github.com/mikelneonedwin/V3",
    description: [
      "Third version of the submission portal for 30DaysOfCodeWithVickyJay",
      "Built with Nuxt and Vue, improved structure and responsiveness",
    ],
    technologies: ["Nuxt", "Vue", "TypeScript", "TailwindCSS"],
  },
  {
    date: "September 2023",
    title: "30 V2 Submission Portal",
    company: "30DaysOfCodeWithVickyJay",
    location: "Remote",
    website: "https://v2-lac.vercel.app",
    github: "https://github.com/mikelneonedwin/30-V2",
    description: [
      "Second version of the submission portal for 30DaysOfCodeWithVickyJay",
      "Improved UI and performance",
    ],
    technologies: ["Vue", "Vite", "TailwindCSS", "TypeScript", "Nuxt"],
  },
  {
    date: "September 2023",
    title: "JQuiz",
    website: "https://jquiz-gamma.vercel.app",
    github: "https://github.com/mikelneonedwin/jQuiz",
    icon: "https://jquiz-gamma.vercel.app/favicon-32x32.png",
    name: "JQuiz",
    description: [
      "Online programming quiz application created independently",
      "Built to test and practice programming knowledge interactively",
    ],
    technologies: ["TailwindCSS", "Vue", "Nuxt.js", "TypeScript"],
  },
  {
    date: "September 2023",
    title: "AudHub",
    website: "https://audhub.vercel.app",
    description: [
      "Online streaming platform built as a learning project",
      "Explored streaming, ranking algorithms and database integration",
    ],
    technologies: ["Firebase", "HTML", "CSS", "JavaScript"],
  },
  {
    date: "August 2023",
    title: "30 V1 Submission Portal",
    company: "30DaysOfCodeWithVickyJay",
    location: "Remote",
    website: "https://30-vickyjay.vercel.app/",
    github: "https://github.com/mikelneonedwin/30-vickyjay",
    description: [
      "First version of the submission portal for the 30DaysOfCodeWithVickyJay challenge",
      "Handles project submissions and basic project listing",
    ],
    technologies: ["HTML", "CSS", "JavaScript", "TailwindCSS"],
  },
  {
    date: "July - August 2025",
    title: "Planora (Team Lead)",
    company: "School Project",
    location: "University of Uyo",
    website: "https://planora-g9.vercel.app",
    github: "https://github.com/Faculty-of-Computing/planora",
    description: [
      "Event management system built as a school project",
      "Led the team in development and coordination",
      "Implemented event scheduling, management, and tracking features",
    ],
    technologies: [
      "TailwindCSS",
      "Flask",
      "PostgreSQL",
      "Python",
      "HTML",
      "JavaScript",
    ],
  },
];
