export const stack = [
  { label: "HTML", icon: "vscode-icons:file-type-html" },
  { label: "CSS", icon: "vscode-icons:file-type-css" },
  { label: "JavaScript", icon: "logos:javascript" },
  { label: "TypeScript", icon: "logos:typescript-icon" },
  { label: "TailwindCSS", icon: "simple-icons:tailwindcss" },
  { label: "React", icon: "logos:react" },
  { label: "Vue", icon: "logos:vue" },
  { label: "Next.js", icon: "logos:nextjs-icon" },
  { label: "Nuxt", icon: "logos:nuxt-icon" },
  { label: "Astro", icon: "simple-icons:astro" },
  { label: "Vite", icon: "logos:vitejs" },
  { label: "Shadcn", icon: "simple-icons:shadcnui" },
  { label: "Express", icon: "simple-icons:express" },
  { label: "Fastify", icon: "simple-icons:fastify" },
  { label: "Node.js", icon: "logos:nodejs-icon" },
  { label: "Bun", icon: "logos:bun" },
  { label: "PostgreSQL", icon: "logos:postgresql" },
  { label: "SQLite", icon: "vscode-icons:file-type-sqlite" },
  { label: "Supabase", icon: "logos:supabase-icon" },
  { label: "Prisma", icon: "simple-icons:prisma" },
  { label: "Redis", icon: "logos:redis" },
  { label: "Firebase", icon: "logos:firebase" },
  { label: "Vercel", icon: "logos:vercel-icon" },
  { label: "Netlify", icon: "logos:netlify" },
  { label: "Render", icon: "simple-icons:render" },
  { label: "GCP", icon: "logos:google-cloud" },
  { label: "Git", icon: "mdi:git" },
  { label: "GitHub", icon: "mdi:github" },
  { label: "VS Code", icon: "vscode-icons:file-type-vscode" },
  { label: "Rollbar", icon: "simple-icons:rollbar" },
];
